/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './home';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/tabs/tabs.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/tabs/tab.ngfactory';
import * as import21 from 'ionic-angular/config/config';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from 'ionic-angular/navigation/view-controller';
import * as import24 from 'ionic-angular/components/app/app';
import * as import25 from 'ionic-angular/components/menu/menu-controller';
import * as import26 from 'ionic-angular/components/toolbar/toolbar';
import * as import27 from 'ionic-angular/platform/platform';
import * as import28 from 'ionic-angular/navigation/deep-linker';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from '@angular/core/src/linker/component_factory_resolver';
import * as import32 from 'ionic-angular/gestures/gesture-controller';
import * as import33 from 'ionic-angular/transitions/transition-controller';
import * as import34 from 'ionic-angular/components/icon/icon';
import * as import35 from 'ionic-angular/components/button/button';
import * as import36 from 'ionic-angular/components/menu/menu-toggle';
import * as import37 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import38 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import39 from 'ionic-angular/components/navbar/navbar';
import * as import40 from 'ionic-angular/components/tabs/tab';
import * as import41 from 'ionic-angular/components/tabs/tabs';
export class Wrapper_Home {
  context:import0.Home;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.Home(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_Home_Host:import2.RenderComponentType = (null as any);
class _View_Home_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Home_0_4:Wrapper_Home;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Home_Host0,renderType_Home_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Home0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Home_0_4 = new Wrapper_Home(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._Home_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Home_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Home) && (0 === requestNodeIndex))) { return this._Home_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Home_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Home_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_Home_Host === (null as any))) { (renderType_Home_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Home_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomeNgFactory:import10.ComponentFactory<import0.Home> = new import10.ComponentFactory<import0.Home>('page-home',viewFactory_Home_Host0,import0.Home);
const styles_Home:any[] = ([] as any[]);
var renderType_Home:import2.RenderComponentType = (null as any);
class _View_Home0 extends import1.AppView<import0.Home> {
  _el_0:any;
  _Header_0_3:import11.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import12.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import13.Wrapper_Button;
  _MenuToggle_4_5:import14.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import15.Wrapper_ToolbarItem;
  _query_Button_4_0:import16.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import17.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import18.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _ToolbarItem_12_3:import15.Wrapper_ToolbarItem;
  _query_Button_12_0:import16.QueryList<any>;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Button_14_4:import13.Wrapper_Button;
  _text_15:any;
  _el_16:any;
  _Icon_16_3:import17.Wrapper_Icon;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _Button_19_4:import13.Wrapper_Button;
  _text_20:any;
  _el_21:any;
  _Icon_21_3:import17.Wrapper_Icon;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _Tabs_28_4:import19.Wrapper_Tabs;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _Tab_30_4:import20.Wrapper_Tab;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import3.AppElement;
  _Tab_32_4:import20.Wrapper_Tab;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _Tab_34_4:import20.Wrapper_Tab;
  _text_35:any;
  _text_36:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Home0,renderType_Home,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Wrapper_Header(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import23.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import24.App),this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import13.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import13.Wrapper_Button('','',this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import14.Wrapper_MenuToggle(this.parentInjector.get(import25.MenuController),new import22.ElementRef(this._el_4),this.parentInjector.get(import23.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import15.Wrapper_ToolbarItem(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import26.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import16.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import17.Wrapper_Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import18.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import18.Wrapper_ToolbarTitle(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import26.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Pizzerie',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_12,'end','');
    this._ToolbarItem_12_3 = new import15.Wrapper_ToolbarItem(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import26.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_12_0 = new import16.QueryList<any>();
    this._text_13 = this.renderer.createText(this._el_12,'\n     \n      ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'button',(null as any));
    this.renderer.setElementAttribute(this._el_14,'ion-button','');
    this._appEl_14 = new import3.AppElement(14,12,this,this._el_14);
    var compView_14:any = import13.viewFactory_Button0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Button_14_4 = new import13.Wrapper_Button((null as any),'',this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_14),this.renderer);
    this._appEl_14.initComponent(this._Button_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n           ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_16,'name','call');
    this.renderer.setElementAttribute(this._el_16,'role','img');
    this._Icon_16_3 = new import17.Wrapper_Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText((null as any),' \n      ',(null as any));
      compView_14.create(this._Button_14_4.context,[([] as any[]).concat([
        this._text_15,
        this._el_16,
        this._text_17
      ]
    )],(null as any));
    this._text_18 = this.renderer.createText(this._el_12,'\n\n      ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_12,'button',(null as any));
    this.renderer.setElementAttribute(this._el_19,'ion-button','');
    this._appEl_19 = new import3.AppElement(19,12,this,this._el_19);
    var compView_19:any = import13.viewFactory_Button0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Button_19_4 = new import13.Wrapper_Button((null as any),'',this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_19),this.renderer);
    this._appEl_19.initComponent(this._Button_19_4.context,([] as any[]),compView_19);
    this._text_20 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_21,'name','information-circle');
    this.renderer.setElementAttribute(this._el_21,'role','img');
    this._Icon_21_3 = new import17.Wrapper_Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_21),this.renderer);
    this._text_22 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_19.create(this._Button_19_4.context,[([] as any[]).concat([
        this._text_20,
        this._el_21,
        this._text_22
      ]
    )],(null as any));
    this._text_23 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([this._el_12]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11,
        this._text_24
      ]
      )
    ]
    ,(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_27 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_28 = this.renderer.createElement(parentRenderNode,'ion-tabs',(null as any));
    this._appEl_28 = new import3.AppElement(28,(null as any),this,this._el_28);
    var compView_28:any = import19.viewFactory_Tabs0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Tabs_28_4 = new import19.Wrapper_Tabs(this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import24.App),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_28),this.parentInjector.get(import27.Platform),this.renderer,this.parentInjector.get(import28.DeepLinker));
    this._appEl_28.initComponent(this._Tabs_28_4.context,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-tab',(null as any));
    this.renderer.setElementAttribute(this._el_30,'role','tabpanel');
    this.renderer.setElementAttribute(this._el_30,'tabIcon','basketball');
    this.renderer.setElementAttribute(this._el_30,'tabTitle','Pizza');
    this._appEl_30 = new import3.AppElement(30,28,this,this._el_30);
    var compView_30:any = import20.viewFactory_Tab0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Tab_30_4 = new import20.Wrapper_Tab(this._Tabs_28_4.context,this.parentInjector.get(import24.App),this.parentInjector.get(import21.Config),this.parentInjector.get(import29.Keyboard),new import22.ElementRef(this._el_30),this.parentInjector.get(import30.NgZone),this.renderer,this.parentInjector.get(import31.ComponentFactoryResolver),compView_30.ref,this.parentInjector.get(import32.GestureController),this.parentInjector.get(import33.TransitionController),this.parentInjector.get(import28.DeepLinker,(null as any)));
    this._appEl_30.initComponent(this._Tab_30_4.context,([] as any[]),compView_30);
    compView_30.create(this._Tab_30_4.context,([] as any[]),(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-tab',(null as any));
    this.renderer.setElementAttribute(this._el_32,'role','tabpanel');
    this.renderer.setElementAttribute(this._el_32,'tabIcon','podium');
    this.renderer.setElementAttribute(this._el_32,'tabTitle','Fast Food');
    this._appEl_32 = new import3.AppElement(32,28,this,this._el_32);
    var compView_32:any = import20.viewFactory_Tab0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Tab_32_4 = new import20.Wrapper_Tab(this._Tabs_28_4.context,this.parentInjector.get(import24.App),this.parentInjector.get(import21.Config),this.parentInjector.get(import29.Keyboard),new import22.ElementRef(this._el_32),this.parentInjector.get(import30.NgZone),this.renderer,this.parentInjector.get(import31.ComponentFactoryResolver),compView_32.ref,this.parentInjector.get(import32.GestureController),this.parentInjector.get(import33.TransitionController),this.parentInjector.get(import28.DeepLinker,(null as any)));
    this._appEl_32.initComponent(this._Tab_32_4.context,([] as any[]),compView_32);
    compView_32.create(this._Tab_32_4.context,([] as any[]),(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'ion-tab',(null as any));
    this.renderer.setElementAttribute(this._el_34,'role','tabpanel');
    this.renderer.setElementAttribute(this._el_34,'tabIcon','podium');
    this.renderer.setElementAttribute(this._el_34,'tabTitle','Drink');
    this._appEl_34 = new import3.AppElement(34,28,this,this._el_34);
    var compView_34:any = import20.viewFactory_Tab0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Tab_34_4 = new import20.Wrapper_Tab(this._Tabs_28_4.context,this.parentInjector.get(import24.App),this.parentInjector.get(import21.Config),this.parentInjector.get(import29.Keyboard),new import22.ElementRef(this._el_34),this.parentInjector.get(import30.NgZone),this.renderer,this.parentInjector.get(import31.ComponentFactoryResolver),compView_34.ref,this.parentInjector.get(import32.GestureController),this.parentInjector.get(import33.TransitionController),this.parentInjector.get(import28.DeepLinker,(null as any)));
    this._appEl_34.initComponent(this._Tab_34_4.context,([] as any[]),compView_34);
    compView_34.create(this._Tab_34_4.context,([] as any[]),(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n\n',(null as any));
      compView_28.create(this._Tabs_28_4.context,[([] as any[]).concat([
        this._text_29,
        this._el_30,
        this._text_31,
        this._el_32,
        this._text_33,
        this._el_34,
        this._text_35
      ]
    )],(null as any));
    this._text_36 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import35.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import36.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import37.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import38.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import34.Icon) && (16 === requestNodeIndex))) { return this._Icon_16_3.context; }
    if (((token === import35.Button) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Button_14_4.context; }
    if (((token === import34.Icon) && (21 === requestNodeIndex))) { return this._Icon_21_3.context; }
    if (((token === import35.Button) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Button_19_4.context; }
    if (((token === import37.ToolbarItem) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ToolbarItem_12_3.context; }
    if (((token === import39.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Navbar_2_4.context; }
    if (((token === import26.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Header_0_3.context; }
    if (((token === import40.Tab) && (30 === requestNodeIndex))) { return this._Tab_30_4.context; }
    if (((token === import40.Tab) && (32 === requestNodeIndex))) { return this._Tab_32_4.context; }
    if (((token === import40.Tab) && (34 === requestNodeIndex))) { return this._Tab_34_4.context; }
    if (((token === import41.Tabs) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Tabs_28_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._ToolbarItem_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    if (this._Button_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'call';
    this._Icon_16_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    if (this._Button_19_4.detectChangesInternal(this,this._el_19,throwOnChange)) { this._appEl_19.componentView.markAsCheckOnce(); }
    const currVal_11:any = 'information-circle';
    this._Icon_21_3.check_name(currVal_11,throwOnChange,false);
    this._Icon_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    this._Tabs_28_4.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_13:any = this.context.PizzaTab;
    this._Tab_30_4.check_root(currVal_13,throwOnChange,false);
    const currVal_14:any = this.context.Pizza;
    this._Tab_30_4.check_rootParams(currVal_14,throwOnChange,false);
    const currVal_15:any = 'Pizza';
    this._Tab_30_4.check_tabTitle(currVal_15,throwOnChange,false);
    const currVal_16:any = 'basketball';
    this._Tab_30_4.check_tabIcon(currVal_16,throwOnChange,false);
    this._Tab_30_4.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_19:any = this.context.PizzaTab;
    this._Tab_32_4.check_root(currVal_19,throwOnChange,false);
    const currVal_20:any = this.context.Pizza;
    this._Tab_32_4.check_rootParams(currVal_20,throwOnChange,false);
    const currVal_21:any = 'Fast Food';
    this._Tab_32_4.check_tabTitle(currVal_21,throwOnChange,false);
    const currVal_22:any = 'podium';
    this._Tab_32_4.check_tabIcon(currVal_22,throwOnChange,false);
    this._Tab_32_4.detectChangesInternal(this,this._el_32,throwOnChange);
    const currVal_25:any = this.context.PizzaTab;
    this._Tab_34_4.check_root(currVal_25,throwOnChange,false);
    const currVal_26:any = this.context.Pizza;
    this._Tab_34_4.check_rootParams(currVal_26,throwOnChange,false);
    const currVal_27:any = 'Drink';
    this._Tab_34_4.check_tabTitle(currVal_27,throwOnChange,false);
    const currVal_28:any = 'podium';
    this._Tab_34_4.check_tabIcon(currVal_28,throwOnChange,false);
    this._Tab_34_4.detectChangesInternal(this,this._el_34,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_12_0.dirty) {
        this._query_Button_12_0.reset([
          this._Button_14_4.context,
          this._Button_19_4.context
        ]
        );
        this._ToolbarItem_12_3.context._buttons = this._query_Button_12_0;
        this._query_Button_12_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_14_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_19_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = this._Icon_16_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_16,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_12:any = this._Icon_21_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_21,'hide',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_17:any = this._Tab_30_4.context._tabId;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementAttribute(this._el_30,'id',((currVal_17 == (null as any))? (null as any): currVal_17.toString()));
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._Tab_30_4.context._btnId;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementAttribute(this._el_30,'aria-labelledby',((currVal_18 == (null as any))? (null as any): currVal_18.toString()));
      this._expr_18 = currVal_18;
    }
    const currVal_23:any = this._Tab_32_4.context._tabId;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementAttribute(this._el_32,'id',((currVal_23 == (null as any))? (null as any): currVal_23.toString()));
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._Tab_32_4.context._btnId;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementAttribute(this._el_32,'aria-labelledby',((currVal_24 == (null as any))? (null as any): currVal_24.toString()));
      this._expr_24 = currVal_24;
    }
    const currVal_29:any = this._Tab_34_4.context._tabId;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementAttribute(this._el_34,'id',((currVal_29 == (null as any))? (null as any): currVal_29.toString()));
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._Tab_34_4.context._btnId;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementAttribute(this._el_34,'aria-labelledby',((currVal_30 == (null as any))? (null as any): currVal_30.toString()));
      this._expr_30 = currVal_30;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Tabs_28_4.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Icon_16_3.context.ngOnDestroy();
    this._Icon_21_3.context.ngOnDestroy();
    this._Tabs_28_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.callIT('tel:+36205600633')) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goInformation()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Home0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.Home> {
  if ((renderType_Home === (null as any))) { (renderType_Home = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_Home,{})); }
  return new _View_Home0(viewUtils,parentInjector,declarationEl);
}