/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './pizza';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import15 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import16 from 'ionic-angular/config/config';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from 'ionic-angular/navigation/view-controller';
import * as import19 from 'ionic-angular/components/app/app';
import * as import20 from 'ionic-angular/components/toolbar/toolbar';
import * as import21 from 'ionic-angular/util/keyboard';
import * as import22 from '@angular/core/src/zone/ng_zone';
import * as import23 from 'ionic-angular/components/tabs/tabs';
import * as import24 from '@angular/core/src/linker/template_ref';
import * as import25 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import26 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import27 from 'ionic-angular/components/navbar/navbar';
import * as import28 from '@angular/common/src/directives/ng_for';
import * as import29 from 'ionic-angular/components/content/content';
import * as import30 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import32 from '@angular/core/src/linker/query_list';
import * as import33 from '../../node_modules/ionic-angular/components/thumbnail/thumbnail.ngfactory';
import * as import34 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import35 from 'ionic-angular/gestures/gesture-controller';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from 'ionic-angular/components/item/item-reorder';
import * as import38 from 'ionic-angular/components/thumbnail/thumbnail';
import * as import39 from 'ionic-angular/components/button/button';
import * as import40 from 'ionic-angular/components/item/item';
import * as import41 from 'ionic-angular/components/list/list';
import * as import42 from '@angular/core/src/security';
export class Wrapper_PizzaPage {
  context:import0.PizzaPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.PizzaPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_PizzaPage_Host:import2.RenderComponentType = (null as any);
class _View_PizzaPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _PizzaPage_0_4:Wrapper_PizzaPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PizzaPage_Host0,renderType_PizzaPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-pizza',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PizzaPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PizzaPage_0_4 = new Wrapper_PizzaPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._PizzaPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._PizzaPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PizzaPage) && (0 === requestNodeIndex))) { return this._PizzaPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PizzaPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PizzaPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_PizzaPage_Host === (null as any))) { (renderType_PizzaPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PizzaPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const PizzaPageNgFactory:import10.ComponentFactory<import0.PizzaPage> = new import10.ComponentFactory<import0.PizzaPage>('page-pizza',viewFactory_PizzaPage_Host0,import0.PizzaPage);
const styles_PizzaPage:any[] = ([] as any[]);
var renderType_PizzaPage:import2.RenderComponentType = (null as any);
class _View_PizzaPage0 extends import1.AppView<import0.PizzaPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import12.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import13.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import14.Wrapper_Content;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _TemplateRef_12_5:any;
  _NgFor_12_6:import15.Wrapper_NgFor;
  _text_13:any;
  _text_14:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PizzaPage0,renderType_PizzaPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import11.Wrapper_Header(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import18.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import19.App),this.parentInjector.get(import18.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import13.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import13.Wrapper_ToolbarTitle(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import20.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'Pizza',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import14.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import14.Wrapper_Content(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import19.App),this.parentInjector.get(import21.Keyboard),this.parentInjector.get(import22.NgZone),this.parentInjector.get(import18.ViewController,(null as any)),this.parentInjector.get(import23.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_12 = new import3.AppElement(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import24.TemplateRef_(this._appEl_12,viewFactory_PizzaPage1);
    this._NgFor_12_6 = new import15.Wrapper_NgFor(this._appEl_12.vcRef,this._TemplateRef_12_5,this.parentInjector.get(import25.IterableDiffers),this.ref);
    this._text_13 = this.renderer.createText((null as any),'\n \n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._appEl_12,
        this._text_13
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import27.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import20.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import24.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import28.NgFor) && (12 === requestNodeIndex))) { return this._NgFor_12_6.context; }
    if (((token === import29.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_3:any = this.context.pizzas;
    this._NgFor_12_6.check_ngForOf(currVal_3,throwOnChange,false);
    this._NgFor_12_6.detectChangesInternal(this,this._anchor_12,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_10_4.context.ngOnDestroy();
  }
}
export function viewFactory_PizzaPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.PizzaPage> {
  if ((renderType_PizzaPage === (null as any))) { (renderType_PizzaPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_PizzaPage,{})); }
  return new _View_PizzaPage0(viewUtils,parentInjector,declarationEl);
}
class _View_PizzaPage1 extends import1.AppView<any> {
  _el_0:any;
  _List_0_3:import30.Wrapper_List;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import31.Wrapper_Item;
  _ItemContent_2_5:import31.Wrapper_ItemContent;
  _query_Label_2_0:import32.QueryList<any>;
  _query_Button_2_1:import32.QueryList<any>;
  _query_Icon_2_2:import32.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Thumbnail_4_3:import33.Wrapper_Thumbnail;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Button_15_4:import34.Wrapper_Button;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PizzaPage1,renderType_PizzaPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_0_3 = new import30.Wrapper_List(this.parent.parentInjector.get(import16.Config),new import17.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import35.GestureController));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import31.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import31.Wrapper_Item(this.parent.parentInjector.get(import36.Form),this.parent.parentInjector.get(import16.Config),new import17.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import37.ItemReorder,(null as any)));
    this._ItemContent_2_5 = new import31.Wrapper_ItemContent();
    this._query_Label_2_0 = new import32.QueryList<any>();
    this._query_Button_2_1 = new import32.QueryList<any>();
    this._query_Icon_2_2 = new import32.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-thumbnail',(null as any));
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this._Thumbnail_4_3 = new import33.Wrapper_Thumbnail();
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'img',(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'clear','');
    this.renderer.setElementAttribute(this._el_15,'ion-button','');
    this.renderer.setElementAttribute(this._el_15,'item-right','');
    this._appEl_15 = new import3.AppElement(15,2,this,this._el_15);
    var compView_15:any = import34.viewFactory_Button0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Button_15_4 = new import34.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import16.Config),new import17.ElementRef(this._el_15),this.renderer);
    this._appEl_15.initComponent(this._Button_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'View',(null as any));
    compView_15.create(this._Button_15_4.context,[([] as any[]).concat([this._text_16])],(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11,
        this._el_12,
        this._text_14,
        this._text_17
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_15])
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n \n ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.Thumbnail) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Thumbnail_4_3.context; }
    if (((token === import39.Button) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Button_15_4.context; }
    if (((token === import40.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Item_2_4.context; }
    if (((token === import40.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ItemContent_2_5.context; }
    if (((token === import41.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._List_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._List_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this._Thumbnail_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_3:any = '';
    this._Button_15_4.check_clear(currVal_3,throwOnChange,false);
    if (this._Button_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([this._Button_15_4.context]);
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.image,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import42.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_10,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.price,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_13,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PizzaPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PizzaPage1(viewUtils,parentInjector,declarationEl);
}